### ISSUE TITLE
Undefined property: Illuminate\Notifications\AnonymousNotifiable::$id

### ISSUE THREAD

**Issue by eleftrik** [jamesmills/laravel-notification-rate-limit#17]
## Versions
Laravel: 8.78.1
jamesmills/laravel-notification-rate-limit: 1.1.0

## Steps to reproduce
- install the package and publish the configuration file (default values)
- update `MyNotification` (fancy name):

```
class MyNotification extends Notification implements ShouldQueue, ShouldRateLimit
{
    use Queueable;
    use RateLimitedNotification;
...
```

In a service class, I'm sending an on-demand notification `MyNotification`:

```php
Notification::route('discord', 'my-channel-id')->notify(app(MyNotification::class));
````

I got this error:

```php
   ErrorException

  Undefined property: Illuminate\Notifications\AnonymousNotifiable::$id

  at vendor/jamesmills/laravel-notification-rate-limit/src/RateLimitedNotification.php:29
     25▕         $parts = array_merge(
     26▕             [
     27▕                 config('laravel-notification-rate-limit.key_prefix'),
     28▕                 class_basename($notification),
  ➜  29▕                 $notifiables->id,
     30▕             ],
     31▕             $this->rateLimitCustomCacheKeyParts(),
     32▕             $this->rateLimitUniqueueNotifications($notification)
     33▕         );
```

I tried to remove any dependency in the notification constructor, but nothing changed.

Without using `ShouldRateLimit` and `RateLimitedNotification`, notifications are sent (but Discord is sending a 429 response, which is the reason why I'm using this package).

Thank you

**Comment by tibbsa** [comment]
@eleftrik  I do not know if this is still an issue for you but it has been resolved.  Due to testing dependencies, supporting L9/10 required dropping support for L8 which you were (at the time) using.  But if it is, and this fix will help, but you are still on Laravel 8, let me know and I will back-port to the 1.x branch.

**Comment by eleftrik** [comment]
> @eleftrik I do not know if this is still an issue for you but it has been resolved. Due to testing dependencies, supporting L9/10 required dropping support for L8 which you were (at the time) using. But if it is, and this fix will help, but you are still on Laravel 8, let me know and I will back-port to the 1.x branch.

Thanks for your time and interest. I'm not on L8 anymore.
