### ISSUE TITLE
Additional contributors?

### ISSUE THREAD

**Issue by tibbsa** [jamesmills/laravel-notification-rate-limit#21]
@jamesmills  - There was some discussion in a pull request thread about the need for some maintainer assistance on this project.  (Tagging @3m1n3nc3 @Riley19280 @samtlewis on this.)

I see there are various forks but nobody seems to have actually "taken over". I happen to need this across multiple projects and would be willing to step up and take on a coordinating role here if that will  help move some of the issues forward.  Whether you want to "transfer" it or simply add me as an additional maintainer is up to you, but I am indifferent.  You can stay in lurk mode.

**Comment by 3m1n3nc3** [comment]
This is one simple project important enough to stay maintained. Just wondering if the author is still **internetly** alive.

**Comment by jamesmills** [comment]
> @jamesmills - There was some discussion in a pull request thread about the need for some maintainer assistance on this project. (Tagging @3m1n3nc3 @Riley19280 @samtlewis on this.)
> 
> I see there are various forks but nobody seems to have actually "taken over". I happen to need this across multiple projects and would be willing to step up and take on a coordinating role here if that will help move some of the issues forward. Whether you want to "transfer" it or simply add me as an additional maintainer is up to you, but I am indifferent. You can stay in lurk mode.

I've added @tibbsa as a contributor.
